In [10]:
import numpy as np

In [11]:
A = np.array([[1,2,3,4],[4,5,6,7]])

In [30]:
print(A.shape[-1])
print(np.reshape(A,(-1,A.shape[-1])))

4
[[1 2 3 4]
 [4 5 6 7]]


In [25]:
B

array([4, 5, 6, 7])

In [24]:
min_value = np.zeros(shape=4)
B
min_value

array([0., 0., 0., 0.])

In [18]:
S = A * B
print()

[[ 4 10 18 28]
 [16 25 36 49]]
